version: '3'

services:
  frontend-angular:
    build:
      context: ./frontend-angular
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8081:8080"

